version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      TZ: "Asia/Taipei"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: NFT
      MYSQL_USER: backend
      MYSQL_PASSWORD: backend
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    environment:
      TZ: "Asia/Taipei"
    build:
      context: .
      dockerfile: dockerFile-backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    links:
      - mysql
